apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositeuserteams.github.jerrymccollom.io
  labels:
    provider: provider-sample
spec:
  compositeTypeRef:
    apiVersion: github.jerrymccollom.io/v1alpha1
    kind: CompositeUserTeam
  resources:
    - base:
        apiVersion: org.github.jerrymccollom.io/v1alpha1
        kind: Team
        spec:
          forProvider:
            org: mccolloms-net
            description: "A composed team."
            privacy: secret
      patches:
      - fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
        toFieldPath: "metadata.name"
      - fromFieldPath: "spec.org"
        toFieldPath: "spec.forProvider.org"
    - base:
        apiVersion: org.github.jerrymccollom.io/v1alpha1
        kind: Membership
        spec:
          forProvider:
            org: mccolloms-net
            teamSelector:
              matchControllerRef: true
            user: jerrymccollom
      patches:
      - fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
        toFieldPath: "metadata.name"
      - fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
        toFieldPath: "spec.forProvider.team"
      - fromFieldPath: "spec.org"
        toFieldPath: "spec.forProvider.org"
      - fromFieldPath: "spec.user"
        toFieldPath: "spec.forProvider.user"

